### ISSUE TITLE
[BUG] 进阶篇

### ISSUE THREAD

**Issue by Albresky** [hugo-fixit/docs#35]
|Field|Value|
|-|-|
|Title|进阶篇|
|URL|https://fixit.lruihao.cn/zh-cn/documentation/advanced/|
|Filename|https://github.com/hugo-fixit/docs/blob/main/content/zh-cn/documentation/advanced/index.md?plain=1|

**Comment by Lruihao** [comment]
请问这篇文档有什么问题吗？
