### ISSUE TITLE
我觉得languages.toml文件或许还能拆分

### ISSUE THREAD

**Issue by Mejituu** [hugo-fixit/docs#5]
我有点想拆分 languages.toml 文件为 languages.toml menus.en.toml menus.zh-cn.toml params.en.toml params.zh-cn.toml 。
如果你愿意的话那我就提交pr😂，正好准备使用你的主题

**Comment by Lruihao** [comment]
我之前拆过languages.toml好像不行，你本地调试一下，如果这样拆分可以的话，就直接提交pr
